version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
  production:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - run: chmod a+x deploy.sh
      - run: ./deploy.sh
workflows:
  version: 2.1
  test:
    jobs:
      - test
      #      - build
      - production:
          requires:
            - test
          filters:
            branches:
              only: prod
