version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2.1
  test:
    jobs:
      - test
      - build
