version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
  build:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2.1
  test:
    jobs:
      - test
#      - build
